### ISSUE TITLE
Finding Visual C++ compiler for Python with CMake (on appveyor)

### ISSUE THREAD

**Issue by msarahan** [scikit-build/scikit-build#34] opened 2016-05-13 16:05 UTC
Greetings, this is a copy of a message I posted to the cmake mailing list, but got no love there.  Since you all are closer to this topic, I hope you might know something helpful.

In compiling TBB, a conda-forge contributor ran across issues with CMake not finding the VS compiler for VS 2008 Win64: https://github.com/conda-forge/staged-recipes/pull/533

The exact error is at https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.2118/job/t2axdaotmty35j6k#L216

Appveyor is an interesting platform, in that they install VS 2008 Express, then the VS compiler for Python (which adds the 64-bit compilation support).

I have been able to fix this in conda-build's test suite by adding some extra registry information and copying some files: https://github.com/conda/conda-build/blob/master/appveyor.yml#L71-L74

Is our version of cmake too old?  Is there some other way we can teach CMake to look in the right place, so that that ugly hack of editing the registry is not necessary?

**Comment by scopatz** [comment] 2016-05-13 20:58
Any help resolving this would be greatly appreciated!

**Comment by opadron** [comment] 2016-06-06 16:03
Hi, guys.  Sorry I haven't taken a look at this, yet, but I want you to know this is on my radar.

I'm working on preparing a (mostly unrelated) skbuild change set for QA (look out for that, soon).  Once that's out of the way, I'll take a closer look at this.

**Comment by opadron** [comment] 2016-07-01 02:51
Oh wow, so in working on the latest topic branch (latest version in #43), I ended up running into the same issue, and also ended up finding @patricksnape's fix.  You'll find my "discovery" [here](https://github.com/scikit-build/scikit-build/pull/38#issuecomment-228079982) (complete with a mini-rant).

Based on the CMake mailing list [link](https://cmake.org/pipermail/cmake/2009-October/032520.html) in that comment, I had believed that this was a Visual Studio problem.  But taking a closer look at your discussion [here](https://github.com/msarahan/conda-build/commit/a236bdbb80f3eba15eff2538c7a79d7dff0aabc6), it looks like I just don't know enough about the details of Visual Studio and its Python support.

@msarahan, would you mind explaining what it is you think needs to change in CMake in order to properly handle this case?  If not `cl.exe`, then is there a different binary, or other files that it should be looking for?

**Comment by jcfr** [comment] 2016-07-01 03:18
> other way we can teach CMake to look in the right place
> that it is you think needs to change in CMake

I think this file that could potentially be updated is https://github.com/Kitware/CMake/blob/master/Source/cmGlobalVisualStudio9Generator.cxx

That said, now we will have a [ci/appveyor/driver.py](https://github.com/opadron/scikit-build/blob/rebased-testing-2016-06-06/ci/appveyor/driver.py), I wonder if:
* it  makes sense to teach CMake how to work with a broken install of VSExpress 2008. Considering CMake generates solution file ... I am not even sure it is possible to make things work for 64-bit without updating the registry and moving files around
* it is the role of CMake to fix a compiler install


Now scikit-build will provide a nice ``

**Comment by opadron** [comment] 2016-07-01 19:20
@jcfr, that was more-or-less my take on the issue, but I just want to make sure that the heart of the issue *is*, in fact, a *defect* in VSExpress 2008 (one requiring registry hacks to work around), and not an *edge-case* that CMake could be taught to recognize.

**Comment by jcfr** [comment] 2016-07-01 21:15
Adding 64-bit support is an after thought ... see https://en.wikipedia.org/wiki/Microsoft_Visual_Studio_Express#Visual_C.2B.2B_Express

![wikipedia-vs2008express](https://cloud.githubusercontent.com/assets/219043/16534647/5c676424-3faf-11e6-9769-74102fd76dfd.png)

**Comment by blowekamp** [comment] 2016-07-01 22:00
It is my understanding that VS9 Express was handicapped with out 64-bit support and many optimizations when compared to VS9 Professional. Hacking the registry may be considering bypassing this intensional handicap.

My understanding is that the" MS Visual C++ compiler for Python" 2.7 is the one to go to when VS9 Professional is not available.

HTH

**Comment by jcfr** [comment] 2016-07-01 22:10
Thanks @blowekamp 

We went in a rabbit whole with the current approach ... 

Otherwise the VS2008 for Python is here: https://www.microsoft.com/en-us/download/details.aspx?id=44266

It should be installable for the current user (without elevated privilege) with `msiexec /i <path to MSI>`

**Comment by msarahan** [comment] 2016-07-01 22:21
Yeah, the VC for Python is totally the way to go.  skbuild (and CMake, ideally) should look for that first, and fall back to looking for VS.  That's what distutils does, I think.

**Comment by jcfr** [comment] 2016-07-01 23:57
@msarahan Reading your original comment, you mentioned ... 

> Appveyor is an interesting platform, in that they install VS 2008 Express, then the VS compiler for 
> Python (which adds the 64-bit compilation support).

Looking at these two links confirm this:
* https://www.appveyor.com/docs/installed-software#python
* https://www.appveyor.com/docs/installed-software#visual-studio-2008

then you added ... 

> have been able to fix this in conda-build's test suite by adding some extra registry information and 
> copying some files: https://github.com/conda/conda-build/blob/master/appveyor.yml#L71-L74

My current understanding is that to workaround the CMake configure error reported for [conda-forge tbb recipe](https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.2118/job/t2axdaotmty35j6k#L216) ,  you are applying the same hack that we now generalized in `ci/appveyor/driver.py`. 

and finally ... 

> skbuild (and CMake, ideally)  should look for [MS C++ Compiler for Python 2.7] first, and fall back to looking for VS. That's what distutils does.

Makes sense.

Since the `MS C++ Compiler for Python 2.7` provides:
* `vcvars.bat`, `vcvars86.bat` and `vcvars64.bat` 
* along side the the `nmake.exe` executable

=> CMake should already support it ! This is confirmed with the experiment results report below.

Conclusion: There is no need to change CMake, it supports `MS C++ Compiler for Python 2.7` out of the box.

What does this mean for `scikit-build` ? 

* When compiling on Windows with Python 2.7:
  1. Look for `C:\Program Files (x86)\Microsoft\Visual C++ for Python\9.0\vcvars.bat`
  2. Depending on the bitness of python interpreter, set the env calling either `vcvars.bat x86` or `vcvars.bat x64`  (or `C:\Program Files (x86)\Microsoft\Visual C++ for Python\9.0\VC\bin\vcvars(64|86).bat` if more convenient)
  3. Invoke CMake to configure  (Specify `-DCMAKE_BUILD_TYPE=Release`)
  4. Then invoke CMake --build /path/to/proj-build

If `Visual C++ for Python` is not available, suggest to download and install it.

Case where applying the workaround would potentially be needed:
* Use of OpenMP ? 

![ms-cpp-compiler-for-python-with-cmake-and-name](https://cloud.githubusercontent.com/assets/219043/16536755/1e92efe6-3fc4-11e6-9745-66fedbef9f25.png)

**Comment by jcfr** [comment] 2016-07-02 00:01
Neat trick: 
* To introspect and extract msi achives. This tool is convenient: http://lessmsi.activescott.com/

**Comment by patricksnape** [comment] 2016-07-05 16:47
@jcfr That 'trick' only works if you use the NMake generator - if you try and use just the Visual Studio 2008 generator then it fails to recognise that the Python tools are providing the interface as CMake explicitly looks for `devenv.com` (in contrast to the VS2010 generator that looks for [msbuild.exe](https://github.com/Kitware/CMake/blob/7d2a0aa76c25d92f1e2a03778f5666bdd7e56b92/Source/cmGlobalVisualStudio10Generator.cxx#L359)).

**Comment by jcfr** [comment] 2016-07-05 17:11
Thanks for your feedback.  Here are few additional comments:

> only works if you use the NMake generator

Since neither `devenv.exe` or `msibuild.exe` are provided by [Microsoft Visual C++ Compiler for Python 2.7](https://www.microsoft.com/en-us/download/details.aspx?id=44266), setting the environment and using NMake generator looks like a reasonable approach.

For that reason, I would not qualify this as a `trick`, instead it should be considered as the recommended way to use `Microsoft Visual C++ Compiler for Python 2.7`

> if you try and use just the Visual Studio 2008 generator then it fails to recognise that the Python tools are providing the interface as CMake explicitly looks

Since visual studio is not provided by `Microsoft Visual C++ Compiler for Python 2.7`, you should not expect `Visual Studio generator` to work.

> as CMake explicitly looks for devenv.com (in contrast to the VS2010 generator that looks for msbuild.exe).

For convenience, CMake suggest a generator based on the platform. That said, the developer have to ultimately choose which one to use.

Let me know what you think,

**Comment by opadron** [comment] 2016-07-05 18:35
So, reading through all these notes, I'm wondering what the way forward is.

Visual Studio is the toolchain suggested for Python, but @jcfr's suggestion for scikit-build is to deviate from the recommended generators and use NMake?  Should we do this across the board for Windows builds?

If we have Visual Studio as well as the Compiler for Python, should we not be able to use both?  My read of all this so far is that this is the scenario that currently requires registry mods, but @patricksnape's suggestion is that such mods would not be necessary if the VS2008 generator in CMake can be updated to look for msbuild.exe, just as the VS2010 generator does?

If this understanding is right, then it seems to me that this issue should be upstreamed to the CMake team.  On our end, we have multiple options for working around the issue (including doing nothing, btw, since we are already using the registry fix when testing), but there is still evidence of an improvement that can be made to CMake, proper.

So, perhaps we should proceed on two fronts:
  1. Prepare and submit an issue to CMake to detect and use the C++ Compiler for Python in the VS2008 Generator.
  1. Explore a better work around in scikit-build while we wait for the improvement to land, the better work around most likely being a temporary switch to the NMake Generator.

Then, after a fix lands in CMake, we can undo the switch and go back to using VS generators across the board?

**Comment by jcfr** [comment] 2016-07-05 19:03
> scikit-build is to deviate from the recommended generators and use NMake? 

Since the documentation for python [has NOT been updated](https://github.com/python/cpython/commits/2.7/Doc/using/windows.rst) accordingly since Microsoft announce the availability of `Microsoft Visual C++ Compiler for Python 2.7` in Sept 2014, I think proposing an update to the official python documentation is reasonable.

> Should we do this across the board for Windows builds?

No. For python 3.x, developing using VisualStudio is very convenient.

> Visual Studio as well as the Compiler for Python, should we not be able to use both?

Yes.

for 2.7, the plan would be to:
* Check if VS2008 x64 is available
* If not check if `Microsoft Visual C++ Compiler for Python 2.7` is available
* If nothing is available .. suggest user to download the compiler for python

> CMake to detect and use the C++ Compiler for Python in the VS2008 Generator

I don't think introducing a dedicated generated named 'Microsoft Visual C++ Compiler for Python 2.7' is worth the effort .. setting the environment and using NMake generator works.

**Comment by patricksnape** [comment] 2016-07-05 20:09
The only disadvantage of the NMake build is the lack of multi-core building.

**Comment by thewtex** [comment] 2016-07-30 15:00
The lack of parallel builds in this situation  is motivation to package Ninja and use it as the default generator. Even if it does not support Fortran yet, it still may be the best default.

**Comment by opadron** [comment] 2016-08-01 18:08
Are there *any* generators that support Fortran on Windows?

I'd rather have a default generator that builds sequentially than not at all.

**Comment by jcfr** [comment] 2016-11-24 06:03
Closing. This issue is now superseded by https://github.com/scikit-build/scikit-build/issues/216

**Closed by jcfr** 2016-11-24 06:03 UTC
