### ISSUE TITLE
Windows: Python 2.7 library not found when installed in virtualenv

### ISSUE THREAD

**Issue by msmolens** [scikit-build/scikit-build#119] opened 2016-08-09 15:58 UTC
On Windows/Python2.7 with scikit-build installed in a virtualenv, `cmaker.get_python_library()` doesn't find python27.lib.

**Comment by jcfr** [comment] 2016-09-11 02:04
@msmolens I am not able to reproduce the issue (using pytest-virtualenv), do you have a set of steps allowing to recreate the problem ?

**Comment by msmolens** [comment] 2016-09-20 15:56
I have not tried pytest-virtualenv, but I can reproduce this with a manually-created virtualenv using the following steps:

    C:\Python27\python.exe --version
    Python 2.7.12

    C:\Python27\scripts\pip install virtualenv
    cd C:\venvs
    C:\Python27\scripts\virtualenv skbuild
    skbuild\Scripts\activate.bat
    cd C:\path\to\scikit-build
    pip install -r requirements.txt
    pip install -r requirements-dev.txt
    pip install -e .
    pytest tests\test_cmaker.py::test_get_python_library

    ================================== FAILURES ===================================
    ___________________________ test_get_python_library ___________________________

        def test_get_python_library():
            python_library = CMaker.get_python_library(CMaker.get_python_version())
    >       assert python_library
    E       assert None

    tests\test_cmaker.py:28: AssertionError
    ========================== 1 failed in 0.37 seconds ===========================

**Comment by jcfr** [comment] 2016-12-14 06:40
For reference, a patch to fix virtualenv has been submitted as https://github.com/pypa/virtualenv/pull/992

**Comment by jcfr** [comment] 2016-12-19 12:39
The fix consisted in updating `skbuild.cmaker` to use `distutils.sysconfig` instead of the standard `sysconfig`. 

Indeed, the `distutils` version is patched by `virtualenv` >= 0.9.2.
See https://virtualenv.pypa.io/en/latest/changes/#id78

Alternatively, integrating pypa/virtualenv#992 into  upstream `virtualenv` would also avoid patching distutils.sysconfig.

**Comment by jcfr** [comment] 2016-12-19 17:16
Fixed by https://github.com/scikit-build/scikit-build/commit/aa51be56eb49c4bc36686bfdc56a5499d12eab05

**Closed by jcfr** 2016-12-19 17:16 UTC
Labels: backlog, bug
